name: 'healthcare_fraud_detection'
version: '1.0.0'
config-version: 2

profile: 'healthcare_fraud_detection'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_fraud_detection:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  healthcare_fraud_detection:
    +quote_columns: false
